/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={1} decay={2} distance={383} color="#19ffce" position={[-61.76, 169.23, -37.21]} />
      <pointLight intensity={1} decay={2} distance={418} color="#ff1e8f" position={[-171.28, 184.31, 97.31]} />
      <pointLight intensity={1} decay={2} distance={2000} position={[-544.91, 422.93, 440]} />
      <OrthographicCamera makeDefault={false} far={100000} near={-100000} position={[-591.88, -442.15, 673.93]} rotation={[0.58, -0.63, 0.37]} />
      <mesh geometry={nodes.Icosahedron_3.geometry} material={nodes.Icosahedron_3.material} />
      <mesh geometry={nodes.Icosahedron_2.geometry} material={nodes.Icosahedron_2.material} />
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} />
      <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} position={[3.04, 0.72, 6.25]} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[3.04, 0.72, 6.25]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
